### PR TITLE
Python3 support for ASCII85Decode

### PR DESCRIPTION
**Pull request by jerickbixly**
This is a port of ASCII85Decode to Python3. An issue this addresses is with pdf outputs from reportlab.

Relevant Py3 changes this addresses: http://python3porting.com/problems.html#bytes-strings-and-unicode

### CODE REVIEW

**Comment by jerickbixly** [comment]
Credit of the algorithm here: https://github.com/hsoft/pdfminer3k/blob/master/pdfminer/ascii85.py

**Comment by paternal** [comment]
:+1: I confirm that this pull request solves the problem, both for Python2 and Python3.

**Comment by StoicLoofah** [comment]
:+1: for this change. I am trying to port an application from python2 to python3, and this (or #171 ) would be very helpful.

**Comment by xj9** [comment]
I'm seeing the same issue porting xhtml2pdf from python 2.7 to python 3

**Comment by bwghughes** [comment]
Any chance of this being merged in folks? Please ask if I can assist in any way.

**Comment by JordanReiter** [comment]
Agreed, I just ran into this same error.

**Comment by mstamy2** [comment]
Sorry for the delay - thank you all for implementing/testing this.

**Comment by duccoder** [comment]
best merge, I think should release new minnor version

**Comment by StoicLoofah** [comment]
agreed on getting minor version. It would be very helpful for getting requirements lined up properly with a new version on pip. Thanks to everyone who pitched in!

**Comment by mstamy2** [comment]
I'll prepare a new release - it's long overdue. I've been working on new features such as a test suite and enhanced PDF form support, but I don't think they'll be ready for this release.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Pull request merged**
