### PR TITLE
/DCTDecode stream data

### PR DESCRIPTION
**Pull request by sylvainpelissier**

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sylvainpelissier thanks a lot, you saved my day there. :+1: A simple pass atleast doesn't crash the library.
The downside is that all those images aren't parsed out though!

**Comment by sylvainpelissier** [comment]
@Yenthe666 Do you have example of pdfs with image not parsed ?

**Comment by Yenthe666** [comment]
@sylvainpelissier I went with another approach for now. Apparently it is much faster (and really stable) to parse images from a PDF with the Python library ```ImageMagick``` with for example ```pdfimages -j yourpath/yourimage``` in place of using this.
If you want to I'll try and find that PDF again next saturday.

**Comment by ariddell** [comment]
It would be great to have this. ``pdfimages`` is great but it's not cross-platform.

**Comment by Lubo** [comment]
Hello. What is the status ? Is this going to be merged anytime soon ?

**Comment by wolframteetz** [comment]
Could anybody please merge this???

**Comment by hayatt143** [comment]
@sylvainpelissier @Yenthe666 Hey, I am trying to use the code which extracts all the images from python.And getting NotImplementedError for /DCTDecode. I found that I am using simple PyPDF2 Library.Can you please give me the link to that particular library which resolves this?

**Comment by sylvainpelissier** [comment]
Hi,

Sorry for my late answer. Have you use my script or directly the pypdf
github?

Le 11 déc. 2017 2:15 AM, "hayatt143" <notifications@github.com> a écrit :

@sylvainpelissier <https://github.com/sylvainpelissier> @Yenthe666
<https://github.com/yenthe666> Hey, I am trying to use the code which
extracts all the images from python.And getting NotImplementedError for
/DCTDecode. I found that I am using simple PyPDF2 Library.Can you please
give me the link to that particular library which resolves this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mstamy2/PyPDF2/pull/237#issuecomment-350624582>, or mute
the thread

**Comment by hayatt143** [comment]
Hey Sylvain Pelissier,

I am happy to receive your reply. I am able to run your code fine now. But
It failed to extract all the images when pdf has more number of pages. So
here I am attaching some pdf files which
is not getting extracted by your code. Please have a look. You are a
saviour by the way.

Thank you
Hayat



‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

On Tue, Dec 19, 2017 at 1:59 AM, Sylvain Pelissier <notifications@github.com
> wrote:

> Hi,
>
> Sorry for my late answer. Have you use my script or directly the pypdf
> github?
>

**Comment by sylvainpelissier** [comment]
Hi,

I think you forget to attach the files.

**Comment by hayatt143** [comment]
Hello,
Thank You for pointing it out. Here is the link.

https://1drv.ms/f/s!AnPgw7hXtChUhGuN13uQ9nCUQlbC

Thanks,
Hayat.

‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

On Wed, Dec 20, 2017 at 2:33 AM, Sylvain Pelissier <notifications@github.com
> wrote:

> Hi,
>
> I think you forget to attach the files.
>

**Comment by hayatt143** [comment]
Hello Sir,

First of all a very happy new year to you. I hope you are doing good. I
just wanted to say I was waiting for your response.

Thank you,
Sarwar





<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by sylvainpelissier** [comment]
Thanks for the merge, I think you can also close #21 .

**Comment by damnko** [comment]
Hi, I've just installed PyPDF2 using `pip install PyPDF2` but I still get the error `NotImplementedError: unsupported filter /DCTDecode` on some PDFs. What could be the reason for this?
Currently using Python v3.7.3 with PyPDF2 v1.26.0
Thanks

**Comment by aminHatim** [comment]
@damnko 
Hey,  I had the same error, but was fixed by installing the library from the source code using a `git clone` + `python setup.py install`. 
It looks like this version was not released t PyPi

**Pull request merged**
