### PR TITLE
Test against Python 3.6, PyPy and PyPy3 (stop testing against Python 3.3)

### PR DESCRIPTION
**Pull request by vstoykov**
**tox**

Remove unnecessary definition of `basepython` in tox. All current versions of tox will guess the right Python version automatically. Also drop Python 2.6 and add Python 3.6, PyPy and PyPy3 to envlist

**travis**

Correctly show which Python version is tested. Test against Python 3.6, PyPy, PyPy3 and stop testing against Python 3.3

### CODE REVIEW

**Comment by meshy** [comment]
This would be helpful, to show that this project is still supports modern Python versions. Is there anything that can be done to push this forward?

**Comment by MartinThoma** [comment]
Thank you for your contribution!

I've configured Github Actions. Do you think travis still provides value?

**Comment by meshy** [comment]
From my perspective having the supported python versions in the GHA config is fine! I have no other need for Travis :)

**Comment by MartinThoma** [comment]
I've tried to add pypy and pypy3 to GHA, but that failed:

* pypy: Seems not to be available in GHA
* pypy3: There was a missing depencency (I think it was pytest?)

**Comment by MartinThoma** [comment]
Please also reply to https://github.com/mstamy2/PyPDF2/issues/659 if you're using PyPDF2  - especially if you use pypy :-) That helps me to prioritize what to test / which platforms need to be supported

**Pull request merged**
