### PR TITLE
Add access_permissions and flags:

### PR DESCRIPTION
**Pull request by vchatterji**
https://mail.python.org/pipermail/python-list/2009-July/545916.html

This patch allows more granular control of the permissions on the PDF while protecting it.

### CODE REVIEW

**Comment by mohit-kothari** [comment]
Well thats where i have the problem. Considering the type of users who are using my application setting password to PDF is not a good idea for me. On the other hand I want to allow print but restrict copy and edit as those PDF's contains sensitive information. And if I set the value of flag to `-1852` as mention in above link I am able to implement those restriction without setting the user password.

**Comment by vchatterji** [comment]
Assuming this link is correct:
http://www.verypdf.com/encryptpdf/permissions.htm

It's boolean arithmetic. 3rd bit on is 2^3=8. 4th bit on is 2^4 = 16. 5th bit on is 2^5=32 and so on.
So you could define the flags as:
```
PERM_PRINT = 8
PERM_MODIFY = 16
...
```
Then you could define the permissions as PERM_PRINT | MODIFY for both print and modify.

Don't know about the negative value though. That is strange.

Also, note that a protected document without a password can be opened on Linux and printed.

I haven't worked on this for a while, for my purposes it was sufficient to prevent modification to the document.

But you are right, the method indicated at:
https://mail.python.org/pipermail/python-list/2009-July/545916.html
may be incorrect.

**Comment by mohit-kothari** [comment]
Well the negative value is nothing but the 2's compliment of the value. Also about Linux, as per my requirements I need to allow users to only print. So as far as it only allows to print I am fine with it. I tried some tools on Linux as well as Windows to check if PDF can be edited but it asks for owner password when trying to edit.

**Comment by vchatterji** [comment]
Great! So you could just define the flags and update your pull request:
https://github.com/mstamy2/PyPDF2/pull/420

I'll just close this one then.

**Comment by vchatterji** [comment]
@mohit-kothari I have updated this PR with the changes from the URL. Please try it out.

**Comment by mohit-kothari** [comment]
Great. Works as expected. Will close #420 
Thanks.:)

**Comment by justlookingaround12** [comment]
Hi, I don't know what the policy here is on replying to old threads so I'm sorry in advance if this is not the right thing to do. However when i run the code written by @vchatterji I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\guest\test.py", line 11, in <module>
    writer.encrypt("", "pasword", perm_mask=PyPDF2.PERM_PRINT)
AttributeError: module 'PyPDF2' has no attribute 'PERM_PRINT'
```
I've tried running it from my pip install and also from copying the edited parts from this issue (init, pdf.py and perm.py). 

Any help would be greatly appreciated!

**Comment by vchatterji** [comment]
@justlookingaround12 the permission is defined in this file:
https://github.com/vchatterji/PyPDF2/blob/master/PyPDF2/__init__.py

**Comment by justlookingaround12** [comment]
@vchatterji Thank you so much for getting back to me! I have now replaced __init__.py and added perms.py to my PyPDF2 folder in .../site-packages however I am still getting the no attribute 'PERM_PRINT' error. Anything you could think of that's causing it? 
Thanks again!

**Comment by justlookingaround12** [comment]
@vchatterji I believe I've fixed my issue, thanks for your input!

For anybody else in the future: 
Copy all relevant files into the PyPDF2 folder in your site-packages folder
then, delete the _pycache_ folder! otherwise the new 'changes' won't take effect

**Comment by vchatterji** [comment]
@justlookingaround12 ???

Here is what I did:
```
git clone https://github.com/vchatterji/PyPDF2
cd PyPDF2
python setup.py install
```

Invoke Python shell:
```
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyPDF2
>>> PyPDF2.PERM_PRINT
2052
>>>
```

**Comment by gakki2019** [comment]
great job! thank you so much, guys.

**Pull request closed without merging**
